### ISSUE TITLE
Is it bug ????

### ISSUE THREAD

**Issue by nhutrg1998** [Horea94/Fruit-Images-Dataset#6] opened 2018-06-25 16:51 UTC
![untitled](https://user-images.githubusercontent.com/24264720/41863991-a56f6884-78d2-11e8-9a7c-bafe8e115fc0.png)

- i need help.

**Comment by Horea94** [comment] 2018-06-25 17:29
Hello. It was a bug.
I pushed the fix.
Please try again and see if the issue persists.

**Comment by nhutrg1998** [comment] 2018-06-25 18:12
Thanks. But then i find a next bug like this. Please help me.
![untitled](https://user-images.githubusercontent.com/24264720/41867695-0978f66e-78de-11e8-8a0a-7ebc8e426b4a.png)

**Comment by Horea94** [comment] 2018-06-25 18:17
That is because the useCkpt variable is set to true in the fruit_train_net.py. This means that it tries to continue the training from a previously saved checkpoint. If you did not run the training before, then useCkpt must be set to False.

**Comment by nhutrg1998** [comment] 2018-06-25 18:37
Please help me fix it, I'm not sure what to do with it.
![untitled](https://user-images.githubusercontent.com/24264720/41868820-66217488-78e1-11e8-835a-ddde20e020df.png)

**Comment by Horea94** [comment] 2018-06-25 18:44
The fruit_train_net.py script looks for a folder called "data" at the same level as the "network" folder. In it should be the test-00000-of-00001 and train-00000-of-00001 files obtained from the build_image_data.py script.

**Comment by nhutrg1998** [comment] 2018-06-25 19:00
Oh yeah, Thank you very much.

**Closed** 2018-06-26 04:41 UTC

**Comment by youaremylovemyy** [comment] 2018-06-28 08:56
Hi,when I run fruit_train_net.py It occurs:
![image](https://user-images.githubusercontent.com/24293884/42024186-32a8f33c-7af4-11e8-8d3f-e58ed97512c8.png)

**Comment by Horea94** [comment] 2018-06-28 09:46
From what I know this error code means memory access violation.
I will look into it, but I am not sure that this issue is caused by the fruit_train_net.py script.
Can you provide some details about what scenario you were working with? Such as what classes did you use for the build_image_data.py script?

**Comment by Horea94** [comment] 2018-06-28 14:58
I am unable to replicate this issue on my machine. 
When I run the fruit_train_net.py script it starts the training and continues without error.
Please provide more details.
